### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by kwstasna** [haydenbleasel/photomap#1]
Hello.
I take the instagram token and instagram id properly and paste them to the test.html
but i get an error in the console that 

photomap.js:140        Uncaught TypeError: Cannot read property 'latitude' of null

Any solution?
Thanks a lot!

**Comment by haydenbleasel** [comment]
Probably haven't written a check to see if a location has been set. I'll fix this up.

**Comment by haydenbleasel** [comment]
Hey @kwstasna, this is fixed in `photomap v1.2.1`.
