### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by kwstasna** [haydenbleasel/photomap#2]
Sorry to hit again an issue really i dont want to be a pain in the ass :(

photomap.js:138 

Uncaught TypeError: Cannot read property 'text' of null

**Comment by haydenbleasel** [comment]
Ah jeez, probably another null check. I'll go over all the variables and add null checks while I'm at it :)

**Comment by haydenbleasel** [comment]
Okay I only saw that one remaining. Should be fixed in `v1.2.2`
